### ISSUE TITLE
why HyperEnclave/atc22-ae need kernel version of 5.3.0-28-generic while HyperEnclave/hyperenclave need 5.4.0？ 

### ISSUE THREAD

**Issue by Ariel08081214** [HyperEnclave/atc22-ae#4]
Hello,can you explain why HyperEnclave/atc22-ae need kernel version of 5.3.0-28-generic while HyperEnclave/hyperenclave need version of 5.4.0？ 
I need to do some experiments as showed in your [paper](https://www.usenix.org/system/files/atc22-jia-yuekai.pdf). I follow those steps showed in HyperEnclave/hyperenclave, I installed kernel version 5.4.0 previously， but HyperEnclave/atc22-ae need version of 5.3.0-28-generic? How can I do for my experiment？

**Comment by xianliang66** [comment]
Hi Ariel, thanks for your interest in HyperEnclave. Hyperenclave works on OSes as long as they have the same kernel APIs. You can try to compile the driver on your OS anyways and see whether the compiler complains.

**Comment by Ariel08081214** [comment]
Thanks a lot for your reply. I just want to figure out the reason for two different versions，and the relationship between HyperEnclave/atc22-ae and HyperEnclave/hyperenclave？@xianliang66

**Comment by xianliang66** [comment]
ae is artificial evaluation in the paper reviewing process to prove what we said in the paper is authentic. A third party uses instructions in ae to reproduce the results. As for different versions, I guess it's just because the guy writing ae doc uses a slightly different OS version. It doesn't matter actually :)

**Comment by Ariel08081214** [comment]
Got it ! Thanks again :)
